### ISSUE TITLE
[Menu/Form] Support images in Menu and Form fields

### ISSUE THREAD

**Issue by asafiniu** [Tradeshift/tradeshift-ui#335]
#### Description of feature
Visuals are great.
If we could support images on every menu item, we could help users find stuff faster.
According to an [article by 3M: "POLISHING YOUR PRESENTATION"](http://web.archive.org/web/20001014041642/http://www.3m.com:80/meetingnetwork/files/meetingguide_pres.pdf): 

> [humans] can process visuals 60,000 times faster than text

In addition, menu-item images can help forms look less... well.... formy :)

#### Example use cases and/or Prototype links
One great example is for a Country field on a registration form fit for Suppliers.
Next to each country name we put its flag. That not only helps users find their country faster (assuming we agree with the aforementioned article) but also makes fields stand out and hopefully become more engaging (Country in this example is a required field, hence the attempt to make it more attractive instead of just requiring it like *every* form out there on the web).

#### Designs and/or Prototype screenshots
One optional route I would personally take (just a suggestion, of course) would be to have each of the `<option>` elements under a `<select>` field depict an attribute (e.g. "img") so that
```
<select>
    <option img="img/asaf.png" img-loc="left" value="123">Asaf Nachmany</option>
    <option img="img/jimi.png" img-loc="left" value="345">Jimi Hendrix</option>
</select>
```
Would render menu items that have `"img/asaf.png"` or `"img/jimi.png"` as their images, to the left of their labels (see `img-loc` example).

For that Country field I mentioned above, here are some screenshots:
The Country field menu:
<img width="313" alt="menu" src="https://user-images.githubusercontent.com/3542388/28838577-99fdd45c-76a5-11e7-892e-13e194d5140f.png">

One such menu item:
<img width="298" alt="menu item" src="https://user-images.githubusercontent.com/3542388/28838578-9a0f7aea-76a5-11e7-94d4-d940015e9b5f.png">

The field once a value (Country) has been selected:
<img width="653" alt="selected" src="https://user-images.githubusercontent.com/3542388/28838579-9a143666-76a5-11e7-9886-c8c513c7625e.png">

The flags in this example use the following resources:
[flag-sprites.png](https://drive.google.com/open?id=0Bwug1ANmzwKvQWhJREdqRXFKUkE)
[flag-sprites.css](https://drive.google.com/open?id=0Bwug1ANmzwKvbmw2eV9sdmN5cWc)

**Comment by TimeBomb** [comment]
The country flags implementation here actually leverages a spritesheet and apprioriate matching CSS, so consideration for that in this enhancement request would be appreciated.

**Comment by asafiniu** [comment]
Hi guys! Any updates on this?

**Comment by wiredearp** [comment]
Well, we would first need a designer such as @bomouridsen to look at this, especially since the new color scheme would only allow for pirate flags, but since this is in the nice to have department, and since the components are in a feature freeze while we implement the mentioned new color scheme, I wouldn't expect it any moment now.

I think by the way that the CSS spritesheet that @TimeBomb suggested, even if it may be the optimal solution for performance, would not really fit into a general specification for images in select options. If this was to be implemented in HTML specification, it would something more like what @asafiniu suggested:

```
<select>
    <option img="img/asaf.png" img-loc="left" value="123">Asaf Nachmany</option>
    <option img="img/jimi.png" img-loc="left" value="345">Jimi Hendrix</option>
</select>
```

The problem with that is however that developers rarely handcode the HTML markup for `select` elements nowadays, they usually have some high level abstraction for populating the `select` that doesn't allow for custom attributes such as `img-loc` and this makes the enhancement somewhat tricky in the marketing department.
