### ISSUE TITLE
[Table] Header has 15px padding-right

### ISSUE THREAD

**Issue by tcomboeanu** [Tradeshift/tradeshift-ui#374]
----------------------------
### Bug report

Apparently the header has a padding on the right of 15 px, the same as the scroll width

#### Tradeshift UI version affected
v9.1.1

#### Designs and/or Prototype screenshots
![screen shot 2017-09-06 at 2 29 25 pm](https://user-images.githubusercontent.com/15786269/30113035-a1468ba2-9313-11e7-83ec-9e0564530f55.png)

**Comment by wiredearp** [comment]
Just for information, the header is "indented" to align with the main section, which on Linux and Windows is always equivalently "indented" by the scrollbar (which in these operating systems is always visible). Any right-aligned content in the cell header (although not present in the screenshot) is then aligned with the *cell* below instead of floating on top of the scrollbar. The real question is then: We does OS X now report a scrollbar size of `15` when usually it reports a scrollbar size of `0`?

**Comment by wiredearp** [comment]
Replaced by https://github.com/Tradeshift/tradeshift-ui/issues/390
