### ISSUE TITLE
Pager component doesn't scroll to the next set of pages 

### ISSUE THREAD

**Issue by MirelaPaun** [Tradeshift/tradeshift-ui#377]
#### Tradeshift UI version affected
v9.1.1

#### Expected Behavior
Pager component should scroll to the next set of pages (page > 5)

#### Actual Behavior
Pager component doesn't scroll to the next set of pages (page > 5)

#### Steps to reproduce
Use Pager component for navigating through pages greater than 5.

#### Screenshots (optional)
![paginationbug](https://user-images.githubusercontent.com/28289435/30213800-e06ce132-94b2-11e7-8c2e-9807bf1cf677.gif)

**Comment by wiredearp** [comment]
Until we have this fixed, the workaround is to create the pager:

```
table.pager({
   page: 0 // below 5!
});
```

– and from now on update the `page` property like this:

```
table.pager().page = 23;
```

The same goes for `ts.ui.Footer.pager()`, which I believe that @MirelaPaun is using, even though the Table comes with a built-in pager as seen on http://ui.tradeshift.com/#components/table/paging.html (but perhaps that's because you guys don't use the `table.maximize()` method?)

**Comment by MirelaPaun** [comment]
Thanks @wiredearp . The workaround works for us. :+1:

**Comment by mihaifantana** [comment]
In my case the workaround was to modify also the `init` property of the pager's model with the same value as `page`.
```javascript
ts.ui.get('_pagerSelector_', pager => {
       pager.pages = n;
       pager.page = x;
       pager._model.init = x;
})
```
That worked without first initializing `page` to 0.
