### ISSUE TITLE
[Buttons] Missing designs

### ISSUE THREAD

**Issue by bomouridsen** [Tradeshift/tradeshift-ui#517]
#### P0
- [x] Implement proper button hierarchy 
   - [x] ts-primary
   - [x] ts-secondary
   - [x] ts-tertiary
   - [x] ts-accept
   - [x] ts-warning
   - [x] ts-danger
- [x] Add hover to all buttons
- [x] Icon buttons have no outline (See aside close icon) or fill color
- [x] White background on secondary/tertiary buttons

#### P1
- [ ] Button focus should be an outer border of 2px, See design below
- [ ] White primary and secondary for branded headers
- [ ] Find a way to give Default button a focus state. Design below is a suggestion, but a not perfect solution.

## Designs
[InVsion inspects link](https://tradeshift.invisionapp.com/d/main#/console/12991172/276054178/inspect)

![image](https://user-images.githubusercontent.com/24455813/35564328-14eeb08e-05ba-11e8-8658-087cce5f7b6b.png)

**Comment by wiredearp** [comment]
Note to self:
- Header color
- Primary button color
-- Header primary button color 😬

**Comment by wiredearp** [comment]
@jerf: Are the "button layouts" still relevant ❓ the ones that you can "join" as seen on the bottom of http://localhost:10114/dist/components/buttons/buttons.html. Because if not, we should remove that section from the docs.

But even if they are: These buttons come with a crappy implementation because of IE9. It should be possible nowadays to reimplement them with CSS flexbox, and with a much nicer syntax for users, no more strange `i-t-t` classnames. Assuming this can be done, we should still remove the section temporarily so that nobody uses the old syntax before we can implement them again. The current implementation uses almost 500 lines of CSS just to support the limited amount of permutations we have today, so it is not something we'd want to leave around forever if we have a new and better implementation (more flexible for users and with less lines of code for us).
