### ISSUE TITLE
[Modal] It's just not working

### ISSUE THREAD

**Issue by Chris-Xie** [Tradeshift/tradeshift-ui#571]
Choose the section that applies to you and use the template to help us figure out how we can help you.

----------------------------
### Bug report
http://ui.tradeshift.com/v11/#components/modals/

#### Tradeshift UI version affected
v11

#### Screenshots (optional)

---------------------------

**Comment by wiredearp** [comment]
Thanks for checking it out :+1: but version 11 is not a drop-in replacement :warning: You will need to update the basic page layout according to the instructions found on http://ui.tradeshift.com/v11/#getstarted/layout.html. That's because we switched from JS layout to a pure CSS layout, not least for performance reasons, now that IE11 is the minimum version. If you have an app the is already built, this process can unfortunately take some time; especially since it is very important the the HTML structure is exactly as described (with no extra `div` elements around or inside the required elements).

**Comment by Chris-Xie** [comment]
I see. Does it mean that we also need to fix the layout for the docs site as well? Because the demo in that link is not working.

**Comment by wiredearp** [comment]
Wow, you are right: That is a bug! If you are still prepared to test version 11 (:question:), I shall fix that straight away. The Modal does work in Firefox, which is what I normally use around here, so I assume it is a `z-index` issue (since the Modal header does show up, but the body is hidden).

**Comment by wiredearp** [comment]
@Chris-Xie Please try that again with version `11.0.9`.

**Comment by Chris-Xie** [comment]
It's working now.
