### ISSUE TITLE
Can't scroll down to the bottom on a list in an aside panel

### ISSUE THREAD

**Issue by oichiyama** [Tradeshift/tradeshift-ui#593]
#### Tradeshift UI version affected
v10.0.17

#### Steps to reproduce
1. Make the list on an aside panel 
2. Create some entries on the list
3. Open the aside panel

#### Actual Behavior
Can not scroll down to the bottom

#### Expected Behavior
Should scroll down to the bottom

#### Screenshots (optional)
![screenshot-1](https://user-images.githubusercontent.com/13126099/39028117-f87065c8-448f-11e8-9da8-d0a9c5acd502.png)

#### Others
This issue was transferred from the following JIRA ticket.
https://tradeshift.atlassian.net/browse/ZT-2159

**Comment by oichiyama** [comment]
When will this bug be fixed?

**Comment by wiredearp** [comment]
While starting to recreate the bug, it occurs to me that it may not be a bug since there is actually a somewhat convoluted setup for the Table to behave as expected. It is however not documented anywhere, it is really a disaster, so there is no way for you to know :disappointed:

The Table doesn't render the scrollbar unless you instruct it to do so. The certified way of doing so is to position the Table inside a `div` that defines the size of the Table and is `position:relative`:

```html
<div style="width: 100%; height: 100%; position: relative">
   <div data-ts="Table"></div>
</div>
```
 – you then call the Table `explode` method and the Table will expand to the size of the container *and* enable the scrollbar.
```js
ts.ui.get('#mytable', table => table.explode());
```
This strange approach saves the Table from parsing the CSS and/or inline styles, in theory several times per second, to figure out if the height has been somehow altered to change the default layout of the Table, which is to simply expand forever as new rows get added (so that the page eventually starts scrolling and not the Table itself). This could be done with `height`, `minheight`, `posittion`, flex, grid and what not, so it is not trivial to figure out automatically. 

Can you try that, assuming that it makes any sense :question: 

All work on UI components has been frozen for quite a while we explored other exciting opportunities. Sorry to keep you waiting. The `explode` method can be fitted with a callback argument that will inform you, how many standard sized rows the Table thinks it can fit in the available space:
```js
table.explode(numrows  => alert(`The Table can fit ${numrows} rows!`));
```
Callback is then invoked whenever you resize the window. This will come in handy if (and only if) you are maintaining that Pager *manually*.

**Comment by wiredearp** [comment]
If you are *not* maintaining that Pager yourself, or if you prefer not to do that, you can call the `optimize` method to let the Table do that for you:
```js
table.explode().optimize();
```
In this scenario, you can just feed all your data to the Table and it will then auto-paginate it for you, there is however an upper limit of some tens of thousands of rows you can feed it before it renders slow in IE and eventually throws a stack overflow error also in the real browsers.

**Comment by tynandebold** [comment]
@oichiyama did you try any of the above solutions to solve the problem?
