### ISSUE TITLE
[table] Sorting not working in Task Manager

### ISSUE THREAD

**Issue by DocGroth** [Tradeshift/tradeshift-ui#626]
Choose the section that applies to you and use the template to help us figure out how we can help you.

----------------------------
### Bug report
Table has sorting problems in Japanese. 
Possible preconditions : 
 - Create task in Task Manager, where assignee's name is double byte character
Steps to reproduce:
1) Go to Tenant ID = xxxxxxxxxx in production 
2) Open task manager 
3) Sort by Assignee (change sorting multiple times) 

Sorting is not correct, especially where the assignee's name is Japanese. 
Current behavior:
Tasks are not sorted by assignee 
More info and screenshots here:
https://tradeshift.atlassian.net/browse/ZT-2352

#### Tradeshift UI version affected
v10.0.25

**Comment by tynandebold** [comment]
I've also found in my testing that if a column contains only Japanese characters, nothing happens when you try and sort that column. That's odd. It should at least 'sort' the same Japanese words and put them next to each other, like in this [simple example](https://codepen.io/anon/pen/XPoagV?editors=0012).

**Comment by tynandebold** [comment]
I've fixed this issue with pull [#642](https://github.com/Tradeshift/tradeshift-ui/pull/642).
