### ISSUE TITLE
[DatePicker] onchange is not triggered

### ISSUE THREAD

**Issue by sampi** [Tradeshift/tradeshift-ui#745]
**Describe the bug**
When selecting a date in the aside, the `onchange` handler in React is not called

**To reproduce**
https://jsfiddle.net/p51keb8m/

**Expected behavior**
`onchange` should be triggered

**Framework usage**
React v16.8.2

**Comment by godvsdeity** [comment]
This is not fixed. I investigated a little bit about what's happening and here are my findings:

1. React dom replaces a node's value property(@see [trackValueOnNode](https://github.com/facebook/react/blob/16.8.3/packages/react-dom/src/client/inputValueTracking.js#L73)) so that every time we do something like `node.value = 'some value'` we will update both the tracker's `currentValue` and the node's proto value:
```
    set: function(value) {
      currentValue = '' + value;
      set.call(this, value);
    },
```
2. The `onChange` events are swallowed by the `ChangeEventPlugin` if the tracker's `currentValue` and the node's proto value are not different (@see [updateValueIfChanged](https://github.com/facebook/react/blob/16.8.3/packages/react-dom/src/client/inputValueTracking.js#L129))
3. In ts-ui we do this: `elm.value = this._snapshot = value;` (@see [InputSpirit](https://github.com/Tradeshift/tradeshift-ui/blob/master/src/runtime/js/ts.ui/forms/forms-gui@tradeshift.com/spirits/ts.ui.InputSpirit.js#L32)); which triggers the steps 1 & 2 and our onchange event will be swallowed by `ChangeEventPlugin` due to no difference between tracker's value and node's value

update fiddle with react 16.8.2 and ts-ui 12.6.0: https://jsfiddle.net/aeLgx2hm/
