### ISSUE TITLE
Update tooltip design

### ISSUE THREAD

**Issue by DocGroth** [Tradeshift/tradeshift-ui#763]
@lloydhumphreys Should we change the design or keep it as is for now?
http://ui.tradeshift.com/v12/#components/tooltip/

**Comment by yeetrium** [comment]
Hi TS UI Team,
The current tooltip design is not mobile friendly because mobile devices do not natively support the hover action of a mouse hover.
There is also no question mark or info icon optionally displayed for the tooltip.
Can those new features be taken into consideration if designing the updated tooltip?

Will the tooltip be completely disabled as Leo suggested here?
https://tradeshift.slack.com/archives/C02TX8JJ7/p1552982667033800?thread_ts=1552946028.033000&cid=C02TX8JJ7
